#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer server

sudo ufw allow 1344
sudo apt-get -y update
sudo apt-get install -y haproxy

printf %s "
backend web-backend
        balance roundrobin
        option forwardfor
        server 9318-web-01 18.234.169.28:80 check
	server 9318-web-02 54.209.135.70:80 check
frontend proxynode bind *:80
        mode http
        default_backend web-backend
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy res
