#!/usr/bin/env bash
# ssh config file

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEvn LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDeleteCredencials no
